[tool.poetry]
name = "prototype"
version = "0.1.0"
description = ""
authors = ["cacapon <cacapon.project@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyxel = "^2.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
